spring.application.name=hotdog-backend

# Database Configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:29889:xe
spring.datasource.username=C##DTO_USER
spring.datasource.password=1234

# JPA/Hibernate ??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ezfillstackprojectsecretkey1234567890abcdefghijklmnopqrstuvwxyz